////URLL-version=3;
//// LEARN_REPOLIST.urll
//// https://github.com/seanpm2001/URLL-Specification
//// A list of all Learn repositories by @seanpm2001
//// As of 2024, Tuesday, October 15th

//// ----------------------------------------------------- \\\\

//// Home repository (1)

https://github.com/seanpm2001/Learn

//// ----------------------------------------------------- \\\\

//// Documentation home repository (1)

https://github.com/seanpm2001/Learn_Docs

//// ----------------------------------------------------- \\\\

//// Learn KnowledgeBase repositories (732)

https://github.com/seanpm2001/Learn-1C-Enterprise
https://github.com/seanpm2001/Learn-ABAP
https://github.com/seanpm2001/Learn-ABAP-CDS
https://github.com/seanpm2001/Learn-ABC
https://github.com/seanpm2001/Learn-ABNF
https://github.com/seanpm2001/Learn-ActionScript-3
https://github.com/seanpm2001/Learn-ActionServerPages.NET
https://github.com/seanpm2001/Learn-Ada
https://github.com/seanpm2001/Learn-Agda
https://github.com/seanpm2001/Learn-AGRAN
https://github.com/seanpm2001/Learn-AGS-Script
https://github.com/seanpm2001/Learn-AIDL
https://github.com/seanpm2001/Learn-AL
https://github.com/seanpm2001/Learn-ALGOL
https://github.com/seanpm2001/Learn-Alloy
https://github.com/seanpm2001/Learn-ALS
https://github.com/seanpm2001/Learn-AMPL
https://github.com/seanpm2001/Learn-Amulet
https://github.com/seanpm2001/Learn-AngelScript
https://github.com/seanpm2001/Learn-ANTLR
https://github.com/seanpm2001/Learn-Antlers
https://github.com/seanpm2001/Learn-ApacheConf
https://github.com/seanpm2001/Learn-Apex
https://github.com/seanpm2001/Learn-API-Blueprint
https://github.com/seanpm2001/Learn-AppleScript
https://github.com/seanpm2001/Learn-Arduino
https://github.com/seanpm2001/Learn-ASCIIDoc
https://github.com/seanpm2001/Learn-ASP
https://github.com/seanpm2001/Learn-ASP.NET
https://github.com/seanpm2001/Learn-AspectJ
https://github.com/seanpm2001/Learn-Assembly
https://github.com/seanpm2001/Learn-AssemblyScript
https://github.com/seanpm2001/Learn-Astro
https://github.com/seanpm2001/Learn-Augeas
https://github.com/seanpm2001/Learn-AutoHotKey
https://github.com/seanpm2001/Learn-AutoIt
https://github.com/seanpm2001/Learn-Awk
https://github.com/seanpm2001/Learn-B
https://github.com/seanpm2001/Learn-Ballerina
https://github.com/seanpm2001/Learn-BASIC
https://github.com/seanpm2001/Learn-Batch
https://github.com/seanpm2001/Learn-Batchfile
https://github.com/seanpm2001/Learn-Beef
https://github.com/seanpm2001/Learn-Befunge
https://github.com/seanpm2001/Learn-BennuGD
https://github.com/seanpm2001/Learn-Berry
https://github.com/seanpm2001/Learn-BibTeX
https://github.com/seanpm2001/Learn-Bicep
https://github.com/seanpm2001/Learn-Bikeshed
https://github.com/seanpm2001/Learn-BitBake
https://github.com/seanpm2001/Learn-Blade
https://github.com/seanpm2001/Learn-BlitzBasic
https://github.com/seanpm2001/Learn-BlitzMax
https://github.com/seanpm2001/Learn-BLISS
https://github.com/seanpm2001/Learn-Blockly
https://github.com/seanpm2001/Learn-BlockQL
https://github.com/seanpm2001/Learn-BlooP
https://github.com/seanpm2001/Learn-Boo
https://github.com/seanpm2001/Learn-Boogie
https://github.com/seanpm2001/Learn-Brainfuck
https://github.com/seanpm2001/Learn-BrightScript
https://github.com/seanpm2001/Learn-BrighterScript
https://github.com/seanpm2001/Learn-Bro
https://github.com/seanpm2001/Learn-BSDL
https://github.com/seanpm2001/Learn-C
https://github.com/seanpm2001/Learn-Cadence
https://github.com/seanpm2001/Learn-Cairo
https://github.com/seanpm2001/Learn-CAML
https://github.com/seanpm2001/Learn-Cap-CDS
https://github.com/seanpm2001/Learn-Cap-n-Proto
https://github.com/seanpm2001/Learn-CartoCSS
https://github.com/seanpm2001/Learn-Ceylon
https://github.com/seanpm2001/Learn-CH
https://github.com/seanpm2001/Learn-Chapel
https://github.com/seanpm2001/Learn-Classic-ASP
https://github.com/seanpm2001/Learn-Clean
https://github.com/seanpm2001/Learn-Creole
https://github.com/seanpm2001/Learn-Crystal
https://github.com/seanpm2001/Learn-Clojure
https://github.com/seanpm2001/Learn-CMake
https://github.com/seanpm2001/Learn-CLIPS
https://github.com/seanpm2001/Learn-Closure-Templates
https://github.com/seanpm2001/Learn-Cobra
https://github.com/seanpm2001/Learn-CodeQL
https://github.com/seanpm2001/Learn-CoffeeScript
https://github.com/seanpm2001/Learn-Commenter
https://github.com/seanpm2001/Learn-CommonLisp
https://github.com/seanpm2001/Learn-CommonWorkflowLangage
https://github.com/seanpm2001/Learn-Component-Pascal
https://github.com/seanpm2001/Learn-ColdFusion
https://github.com/seanpm2001/Learn-ColdFusion-CFC
https://github.com/seanpm2001/Learn-Cool
https://github.com/seanpm2001/Learn-Coq
https://github.com/seanpm2001/Learn-CPython
https://github.com/seanpm2001/Learn-C-Plus-Plus
https://github.com/seanpm2001/Learn-COBOL
https://github.com/seanpm2001/Learn-CSharp
https://github.com/seanpm2001/Learn-CSHTML
https://github.com/seanpm2001/Learn-CSound
https://github.com/seanpm2001/Learn-CSound-Document
https://github.com/seanpm2001/Learn-CSound-Score
https://github.com/seanpm2001/Learn-CSON
https://github.com/seanpm2001/Learn-CSS
https://github.com/seanpm2001/Learn-CSV
https://github.com/seanpm2001/Learn-CUDA
https://github.com/seanpm2001/Learn-CUE
https://github.com/seanpm2001/Learn-CWeb
https://github.com/seanpm2001/Learn-Cyclone
https://github.com/seanpm2001/Learn-Cython
https://github.com/seanpm2001/Learn-D
https://github.com/seanpm2001/Learn-Dafny
https://github.com/seanpm2001/Learn-Dart
https://github.com/seanpm2001/Learn-DataWeave
https://github.com/seanpm2001/Learn-DCPU-16-ASM
https://github.com/seanpm2001/Learn-Desktop
https://github.com/seanpm2001/Learn-Dhall
https://github.com/seanpm2001/Learn-Diff
https://github.com/seanpm2001/Learn-DIGITAL-Command-Language
https://github.com/seanpm2001/Learn-DM
https://github.com/seanpm2001/Learn-Dockerfile
https://github.com/seanpm2001/Learn-DogeScript
https://github.com/seanpm2001/Learn-DroppedText
https://github.com/seanpm2001/Learn-DSergeant
https://github.com/seanpm2001/Learn-DTrace
https://github.com/seanpm2001/Learn-Dylan
https://github.com/seanpm2001/Learn-E
https://github.com/seanpm2001/Learn-Eagle
https://github.com/seanpm2001/Learn-Earthly
https://github.com/seanpm2001/Learn-EBNF
https://github.com/seanpm2001/Learn-Eiffel
https://github.com/seanpm2001/Learn-EJS
https://github.com/seanpm2001/Learn-Elixir
https://github.com/seanpm2001/Learn-Elm
https://github.com/seanpm2001/Learn-EmacsLisp
https://github.com/seanpm2001/Learn-Epigram
https://github.com/seanpm2001/Learn-Erlang
https://github.com/seanpm2001/Learn-Ermine
https://github.com/seanpm2001/Learn-Euphoria
https://github.com/seanpm2001/Learn-Ezhil
https://github.com/seanpm2001/Learn-Factor
https://github.com/seanpm2001/Learn-Fancy
https://github.com/seanpm2001/Learn-Fantom
https://github.com/seanpm2001/Learn-FP
https://github.com/seanpm2001/Learn-FCL
https://github.com/seanpm2001/Learn-Fish
https://github.com/seanpm2001/Learn-FlooP
https://github.com/seanpm2001/Learn-Fluent
https://github.com/seanpm2001/Learn-FLUX
https://github.com/seanpm2001/Learn-Forth
https://github.com/seanpm2001/Learn-FORTRAN
https://github.com/seanpm2001/Learn-FreeBasic
https://github.com/seanpm2001/Learn-FreeMarker
https://github.com/seanpm2001/Learn-FSharp
https://github.com/seanpm2001/Learn-FStar
https://github.com/seanpm2001/Learn-Fuzzy-Markup-Language-FML
https://github.com/seanpm2001/Learn-GAP
https://github.com/seanpm2001/Learn-GCC-Machine-Description
https://github.com/seanpm2001/Learn-G-CODE
https://github.com/seanpm2001/Learn-GDB
https://github.com/seanpm2001/Learn-GDScript
https://github.com/seanpm2001/Learn-Gerber-Image
https://github.com/seanpm2001/Learn-Genie
https://github.com/seanpm2001/Learn-GetText
https://github.com/seanpm2001/Learn-Gherkin
https://github.com/seanpm2001/Learn-Gleam
https://github.com/seanpm2001/Learn-GLSL
https://github.com/seanpm2001/Learn-GN
https://github.com/seanpm2001/Learn-GnuPlot
https://github.com/seanpm2001/Learn-Go2003
https://github.com/seanpm2001/Learn-GolfScript
https://github.com/seanpm2001/Learn-Google-Apps-Script
https://github.com/seanpm2001/Learn-GoogleGo
https://github.com/seanpm2001/Learn-Gosu
https://github.com/seanpm2001/Learn-Gradle
https://github.com/seanpm2001/Learn-Grammatical-Framework
https://github.com/seanpm2001/Learn-GRANNY
https://github.com/seanpm2001/Learn-GraphQL
https://github.com/seanpm2001/Learn-GraphViz-DOT
https://github.com/seanpm2001/Learn-Gremlin
https://github.com/seanpm2001/Learn-Groovy
https://github.com/seanpm2001/Learn-GSC
https://github.com/seanpm2001/Learn-Hack
https://github.com/seanpm2001/Learn-Handlebars
https://github.com/seanpm2001/Learn-HAML
https://github.com/seanpm2001/Learn-HaProxy
https://github.com/seanpm2001/Learn-Harbour
https://github.com/seanpm2001/Learn-Haskell
https://github.com/seanpm2001/Learn-Haxe
https://github.com/seanpm2001/Learn-HCL
https://github.com/seanpm2001/Learn-HiveQL
https://github.com/seanpm2001/Learn-HLSL
https://github.com/seanpm2001/Learn-HolyC
https://github.com/seanpm2001/Learn-Hope
https://github.com/seanpm2001/Learn-HTML
https://github.com/seanpm2001/Learn-HTTP
https://github.com/seanpm2001/Learn-HXML
https://github.com/seanpm2001/Learn-Hy
https://github.com/seanpm2001/Learn-HyPhy
https://github.com/seanpm2001/Learn-IDL
https://github.com/seanpm2001/Learn-Idris
https://github.com/seanpm2001/Learn-Inform
https://github.com/seanpm2001/Learn-INI
https://github.com/seanpm2001/Learn-Inno-Setup
https://github.com/seanpm2001/Learn-IntelHexBinary
https://github.com/seanpm2001/Learn-INTERCAL
https://github.com/seanpm2001/Learn-ImageJ
https://github.com/seanpm2001/Learn-Io
https://github.com/seanpm2001/Learn-IronPython
https://github.com/seanpm2001/Learn-Isabelle
https://github.com/seanpm2001/Learn-ISWIM
https://github.com/seanpm2001/Learn-J
https://github.com/seanpm2001/Learn-Jade
https://github.com/seanpm2001/Learn-Jasmin
https://github.com/seanpm2001/Learn-Jakarta-Server-Pages
https://github.com/seanpm2001/Learn-Java
https://github.com/seanpm2001/Learn-JavaScript
https://github.com/seanpm2001/Learn-JavaScriptPlusPlus
https://github.com/seanpm2001/Learn-Java-Server-Pages
https://github.com/seanpm2001/Learn-JetBrains-MPS
https://github.com/seanpm2001/Learn-JFlex
https://github.com/seanpm2001/Learn-Jinja
https://github.com/seanpm2001/Learn-Joy
https://github.com/seanpm2001/Learn-jq
https://github.com/seanpm2001/Learn-JScript
https://github.com/seanpm2001/Learn-JScript.NET
https://github.com/seanpm2001/Learn-JSON
https://github.com/seanpm2001/Learn-JSON5
https://github.com/seanpm2001/Learn-Jsonnet
https://github.com/seanpm2001/Learn-JSSS
https://github.com/seanpm2001/Learn-Julia
https://github.com/seanpm2001/Learn-JupyterNotebook
https://github.com/seanpm2001/Learn-Jython
https://github.com/seanpm2001/Learn-KiCad //// Layout and Schematic (both included as one)
https://github.com/seanpm2001/Learn-KiCad-Layout
https://github.com/seanpm2001/Learn-KiCad-Schematic
https://github.com/seanpm2001/Learn-KiXTart
https://github.com/seanpm2001/Learn-Kotlin
https://github.com/seanpm2001/Learn-KRC
https://github.com/seanpm2001/Learn-kvlang
https://github.com/seanpm2001/Learn-LabVIEW
https://github.com/seanpm2001/Learn-Latte
https://github.com/seanpm2001/Learn-Lean
https://github.com/seanpm2001/Learn-Less
https://github.com/seanpm2001/Learn-Lex
https://github.com/seanpm2001/Learn-Limbo
https://github.com/seanpm2001/Learn-Lingo
https://github.com/seanpm2001/Learn-Linker-Script
https://github.com/seanpm2001/Learn-Linux-Kernel-Module
https://github.com/seanpm2001/Learn-Liquid
https://github.com/seanpm2001/Learn-Lisp
https://github.com/seanpm2001/Learn-LispFlavoredErlang
https://github.com/seanpm2001/Learn-Little
https://github.com/seanpm2001/Learn-LiveCode
https://github.com/seanpm2001/Learn-LiveScript
https://github.com/seanpm2001/Learn-LLVM
https://github.com/seanpm2001/Learn-Lobster
https://github.com/seanpm2001/Learn-Logcat
https://github.com/seanpm2001/Learn-LogTalk
https://github.com/seanpm2001/Learn-LOLCODE
https://github.com/seanpm2001/Learn-Lua
https://github.com/seanpm2001/Learn-Lucid
https://github.com/seanpm2001/Learn-Logos
https://github.com/seanpm2001/Learn-LookML
https://github.com/seanpm2001/Learn-M
https://github.com/seanpm2001/Learn-M4
https://github.com/seanpm2001/Learn-M4Sugar
https://github.com/seanpm2001/Learn-Macaulay2
https://github.com/seanpm2001/Learn-Makefile
https://github.com/seanpm2001/Learn-Mako
https://github.com/seanpm2001/Learn-Malbolge
https://github.com/seanpm2001/Learn-Mallard
https://github.com/seanpm2001/Learn-Markdown
https://github.com/seanpm2001/Learn-Mathematica
https://github.com/seanpm2001/Learn-MATLAB
https://github.com/seanpm2001/Learn-Seanpm2001-Matrix
https://github.com/seanpm2001/Learn-Max
https://github.com/seanpm2001/Learn-Maxima
https://github.com/seanpm2001/Learn-MAXScript
https://github.com/seanpm2001/Learn-McFunction
https://github.com/seanpm2001/Learn-MCPYE-CL
https://github.com/seanpm2001/Learn-MediaWiki
https://github.com/seanpm2001/Learn-Mercury
https://github.com/seanpm2001/Learn-Meson
https://github.com/seanpm2001/Learn-Metal
https://github.com/seanpm2001/Learn-MGears
https://github.com/seanpm2001/Learn-Miranda
https://github.com/seanpm2001/Learn-mIRC-Script
https://github.com/seanpm2001/Learn-ML
https://github.com/seanpm2001/Learn-MLIR
https://github.com/seanpm2001/Learn-Modelica
https://github.com/seanpm2001/Learn-Modula-2
https://github.com/seanpm2001/Learn-Modula-3
https://github.com/seanpm2001/Learn-Module-Management-System
https://github.com/seanpm2001/Learn-Mojo
https://github.com/seanpm2001/Learn-Mojom
https://github.com/seanpm2001/Learn-Monkey
https://github.com/seanpm2001/Learn-Monkey-C
https://github.com/seanpm2001/Learn-MoonScript
https://github.com/seanpm2001/Learn-Motoko
https://github.com/seanpm2001/Learn-MQL4
https://github.com/seanpm2001/Learn-MQL5
https://github.com/seanpm2001/Learn-MS-DOS-Style
https://github.com/seanpm2001/Learn-MTML
https://github.com/seanpm2001/Learn-Mustache
https://github.com/seanpm2001/Learn-NASL
https://github.com/seanpm2001/Learn-Nemerle
https://github.com/seanpm2001/Learn-nesC
https://github.com/seanpm2001/Learn-NetREXX
https://github.com/seanpm2001/Learn-NewLisp
https://github.com/seanpm2001/Learn-NextFlow
https://github.com/seanpm2001/Learn-NGINX
https://github.com/seanpm2001/Learn-Nim
https://github.com/seanpm2001/Learn-Nix
https://github.com/seanpm2001/Learn-Noop
https://github.com/seanpm2001/Learn-NSIS
https://github.com/seanpm2001/Learn-Nu
https://github.com/seanpm2001/Learn-Nunjucks
https://github.com/seanpm2001/Learn-Oberon
https://github.com/seanpm2001/Learn-Objective-C
https://github.com/seanpm2001/Learn-Objective-CPP
https://github.com/seanpm2001/Learn-Objective-CSharp
https://github.com/seanpm2001/Learn-Objective-J
https://github.com/seanpm2001/Learn-Objective-JPlusPlus
https://github.com/seanpm2001/Learn-Objective-JSharp
https://github.com/seanpm2001/Learn-OCaml
https://github.com/seanpm2001/Learn-Octave
https://github.com/seanpm2001/Learn-Ooc
https://github.com/seanpm2001/Learn-OpenCL
https://github.com/seanpm2001/Learn-OpenEdge-ABL
https://github.com/seanpm2001/Learn-OpenPolicyAgent
https://github.com/seanpm2001/Learn-OpenQASM
https://github.com/seanpm2001/Learn-OpenSCAD
https://github.com/seanpm2001/Learn-Orwell
https://github.com/seanpm2001/Learn-OrgMode
https://github.com/seanpm2001/Learn-Oxygene
https://github.com/seanpm2001/Learn-Pascal
https://github.com/seanpm2001/Learn-Pawn
https://github.com/seanpm2001/Learn-PEG.js
https://github.com/seanpm2001/Learn-Perl
https://github.com/seanpm2001/Learn-Perl6
https://github.com/seanpm2001/Learn-PHP
https://github.com/seanpm2001/Learn-PicoLisp
https://github.com/seanpm2001/Learn-PigLatin
https://github.com/seanpm2001/Learn-Plankalk-u-l
https://github.com/seanpm2001/Learn-PlantUML
https://github.com/seanpm2001/Learn-PLpgSQL
https://github.com/seanpm2001/Learn-PLSQL
https://github.com/seanpm2001/Learn-Pod
https://github.com/seanpm2001/Learn-Pod6
https://github.com/seanpm2001/Learn-Pony
https://github.com/seanpm2001/Learn-PostCSS
https://github.com/seanpm2001/Learn-PostGreSQL
https://github.com/seanpm2001/Learn-PostScript
https://github.com/seanpm2001/Learn-POV-Ray-SDL
https://github.com/seanpm2001/Learn-PowerShell
https://github.com/seanpm2001/Learn-PowerFX
https://github.com/seanpm2001/Learn-Procfile
https://github.com/seanpm2001/Learn-Processing
https://github.com/seanpm2001/Learn-Processing.js
https://github.com/seanpm2001/Learn-Proguard
https://github.com/seanpm2001/Learn-Prolog
https://github.com/seanpm2001/Learn-Protocol-Buffer
https://github.com/seanpm2001/Learn-Pug
https://github.com/seanpm2001/Learn-Puppet
https://github.com/seanpm2001/Learn-PureBasic
https://github.com/seanpm2001/Learn-PureData
https://github.com/seanpm2001/Learn-PureScript
https://github.com/seanpm2001/Learn-Python
https://github.com/seanpm2001/Learn-PythonTraceback
https://github.com/seanpm2001/Learn-q
https://github.com/seanpm2001/Learn-QMake
https://github.com/seanpm2001/Learn-QML
https://github.com/seanpm2001/Learn-QSharp
https://github.com/seanpm2001/Learn-QT-Script
https://github.com/seanpm2001/Learn-QueryByExample
https://github.com/seanpm2001/Learn-R
https://github.com/seanpm2001/Learn-Racket
https://github.com/seanpm2001/Learn-Ragel
https://github.com/seanpm2001/Learn-Raku
https://github.com/seanpm2001/Learn-RAML
https://github.com/seanpm2001/Learn-Rascal
https://github.com/seanpm2001/Learn-RDoc
https://github.com/seanpm2001/Learn-Reason
https://github.com/seanpm2001/Learn-ReasonML
https://github.com/seanpm2001/Learn-REBOL
https://github.com/seanpm2001/Learn-Red
https://github.com/seanpm2001/Learn-Refal
https://github.com/seanpm2001/Learn-RenderScript
https://github.com/seanpm2001/Learn-Ren-Py
https://github.com/seanpm2001/Learn-ReScript
https://github.com/seanpm2001/Learn-ReStructuredText
https://github.com/seanpm2001/Learn-REXX
https://github.com/seanpm2001/Learn-RichTextFormat
https://github.com/seanpm2001/Learn-RobotFramework
https://github.com/seanpm2001/Learn-Roff
https://github.com/seanpm2001/Learn-RouterOS-Script
https://github.com/seanpm2001/Learn-RPC
https://github.com/seanpm2001/Learn-RPGLE
https://github.com/seanpm2001/Learn-Ruby
https://github.com/seanpm2001/Learn-RUNOFF
https://github.com/seanpm2001/Learn-Rust
https://github.com/seanpm2001/Learn-Sage
https://github.com/seanpm2001/Learn-SaltStack
https://github.com/seanpm2001/Learn-SAS
https://github.com/seanpm2001/Learn-SASL
https://github.com/seanpm2001/Learn-SASS
https://github.com/seanpm2001/Learn-Scala
https://github.com/seanpm2001/Learn-Scheme
https://github.com/seanpm2001/Learn-SciLab
https://github.com/seanpm2001/Learn-Scratch
https://github.com/seanpm2001/Learn-Scratch-1
https://github.com/seanpm2001/Learn-Scratch-2
https://github.com/seanpm2001/Learn-Scratch-3
https://github.com/seanpm2001/Learn-SCSS
https://github.com/seanpm2001/Learn-SDLang
https://github.com/seanpm2001/Learn-Sed
https://github.com/seanpm2001/Learn-Seed7
https://github.com/seanpm2001/Learn-Self
https://github.com/seanpm2001/Learn-SGML
https://github.com/seanpm2001/Learn-Singularity
https://github.com/seanpm2001/Learn-ShaderLab
https://github.com/seanpm2001/Learn-Shell
https://github.com/seanpm2001/Learn-Slash
https://github.com/seanpm2001/Learn-Slim
https://github.com/seanpm2001/Learn-SmallTalk
https://github.com/seanpm2001/Learn-Smali
https://github.com/seanpm2001/Learn-Smarty
https://github.com/seanpm2001/Learn-SmPL
https://github.com/seanpm2001/Learn-SMT
https://github.com/seanpm2001/Learn-SNOBOL
https://github.com/seanpm2001/Learn-Solidity
https://github.com/seanpm2001/Learn-SourcePawn
https://github.com/seanpm2001/Learn-SQF
https://github.com/seanpm2001/Learn-SQL
https://github.com/seanpm2001/Learn-SQLPL
https://github.com/seanpm2001/Learn-Squeak
https://github.com/seanpm2001/Learn-Squirrel
https://github.com/seanpm2001/Learn-S-RECORD
https://github.com/seanpm2001/Learn-SRecode-Template
https://github.com/seanpm2001/Learn-Stan
https://github.com/seanpm2001/Learn-STAR
https://github.com/seanpm2001/Learn-StandardML
https://github.com/seanpm2001/Learn-Starlark
https://github.com/seanpm2001/Learn-Stata
https://github.com/seanpm2001/Learn-StrictYAML
https://github.com/seanpm2001/Learn-StringTemplate
https://github.com/seanpm2001/Learn-Stylus
https://github.com/seanpm2001/Learn-SublimeText
https://github.com/seanpm2001/Learn-SugarSS
https://github.com/seanpm2001/Learn-SuperCollider
https://github.com/seanpm2001/Learn-Svelte
https://github.com/seanpm2001/Learn-SVG
https://github.com/seanpm2001/Learn-Sweave
https://github.com/seanpm2001/Learn-Swift
https://github.com/seanpm2001/Learn-SWIG
https://github.com/seanpm2001/Learn-SXML
https://github.com/seanpm2001/Learn-SystemVerilog
https://github.com/seanpm2001/Learn-Tampio
https://github.com/seanpm2001/Learn-Tcl
https://github.com/seanpm2001/Learn-Terra
https://github.com/seanpm2001/Learn-TeX
https://github.com/seanpm2001/Learn-Textile
https://github.com/seanpm2001/Learn-Twig
https://github.com/seanpm2001/Learn-Thrift
https://github.com/seanpm2001/Learn-TLA
https://github.com/seanpm2001/Learn-TOML
https://github.com/seanpm2001/Learn-Triton_OpenAI
https://github.com/seanpm2001/Learn-TSQL
https://github.com/seanpm2001/Learn-TSX
https://github.com/seanpm2001/Learn-TXL
https://github.com/seanpm2001/Learn-TypeScript
https://github.com/seanpm2001/Learn-UnrealScript
https://github.com/seanpm2001/Learn-Unity3DAsset
https://github.com/seanpm2001/Learn-Unix-Assembly
https://github.com/seanpm2001/Learn-Uno
https://github.com/seanpm2001/Learn-URLL
https://github.com/seanpm2001/Learn_V
https://github.com/seanpm2001/Learn-Vala
https://github.com/seanpm2001/Learn-VBA
https://github.com/seanpm2001/Learn-VBHTML
https://github.com/seanpm2001/Learn-VBScript
https://github.com/seanpm2001/Learn-VCL
https://github.com/seanpm2001/Learn-Verilog
https://github.com/seanpm2001/Learn-Verilog-AMS
https://github.com/seanpm2001/Learn-Verona
https://github.com/seanpm2001/Learn-VHDL
https://github.com/seanpm2001/Learn-VimScript
https://github.com/seanpm2001/Learn-Vim-Snippet
https://github.com/seanpm2001/Learn-VisualBasicDOTNet
https://github.com/seanpm2001/Learn-VisualBasicScript
https://github.com/seanpm2001/Learn-VisualLogic
https://github.com/seanpm2001/Learn-VueJS
https://github.com/seanpm2001/Learn-Wasp
https://github.com/seanpm2001/Learn-WaveFront-Material
https://github.com/seanpm2001/Learn-WaveFront-Object
https://github.com/seanpm2001/Learn-WDL
https://github.com/seanpm2001/Learn-WebAssembly
https://github.com/seanpm2001/Learn-WebIDL
https://github.com/seanpm2001/Learn-WEB
https://github.com/seanpm2001/Learn-WebVTT
https://github.com/seanpm2001/Learn-While
https://github.com/seanpm2001/Learn-Whitespace
https://github.com/seanpm2001/Learn-Wierd
https://github.com/seanpm2001/Learn-WikiText
https://github.com/seanpm2001/Learn-WindowsRegistry
https://github.com/seanpm2001/Learn-Wisp
https://github.com/seanpm2001/Learn-Wren
https://github.com/seanpm2001/Learn-XBase
https://github.com/seanpm2001/Learn-XBasePlusPlus
https://github.com/seanpm2001/Learn-XML
https://github.com/seanpm2001/Learn-X-Pixmap
https://github.com/seanpm2001/Learn-XProc
https://github.com/seanpm2001/Learn-XQuery
https://github.com/seanpm2001/Learn-XS
https://github.com/seanpm2001/Learn-XSLT
https://github.com/seanpm2001/Learn-XTend
https://github.com/seanpm2001/Learn-Yacc
https://github.com/seanpm2001/Learn-YAML
https://github.com/seanpm2001/Learn-YARA
https://github.com/seanpm2001/Learn-YASnippet
https://github.com/seanpm2001/Learn-ZAP
https://github.com/seanpm2001/Learn-Zeek
https://github.com/seanpm2001/Learn-ZenScript
https://github.com/seanpm2001/Learn-Zig
https://github.com/seanpm2001/Learn-ZIL
//// 207 new entries (sorting needed)
https://github.com/seanpm2001/Learn-CPL
https://github.com/seanpm2001/Learn-FLOW-MATIC
https://github.com/seanpm2001/Learn-Information-Processing-Language
https://github.com/seanpm2001/Learn-ARITH-MATIC
https://github.com/seanpm2001/Learn-asm.js
https://github.com/seanpm2001/Learn-Planner
https://github.com/seanpm2001/Learn-POP-1
https://github.com/seanpm2001/Learn-POP-2
https://github.com/seanpm2001/Learn-MDX
https://github.com/seanpm2001/Learn-SCRIPT
https://github.com/seanpm2001/Learn-Generalized-Markup-Language-GML
https://github.com/seanpm2001/Learn-EasyScript
https://github.com/seanpm2001/Learn-APL
https://github.com/seanpm2001/Learn-CDS
https://github.com/seanpm2001/Learn-CAP
https://github.com/seanpm2001/Learn-Speedcode
https://github.com/seanpm2001/Learn-P-DoublePrime
https://github.com/seanpm2001/Learn-SKILL
https://github.com/seanpm2001/Learn-EJSS
https://github.com/seanpm2001/Learn-MDL
https://github.com/seanpm2001/Learn-Arc
https://github.com/seanpm2001/Learn-Adblock-Filter-List
https://github.com/seanpm2001/Learn-Mermaid
https://github.com/seanpm2001/Learn-VisionScript
https://github.com/seanpm2001/Learn-Smithy
https://github.com/seanpm2001/Learn-Hestia
https://github.com/seanpm2001/Learn-Visual-Basic-6-0
https://github.com/seanpm2001/Learn-EmberScript
https://github.com/seanpm2001/Learn-DenizenScript
https://github.com/seanpm2001/Learn-Marko
https://github.com/seanpm2001/Learn-ASN.1
https://github.com/seanpm2001/Learn-ActionMessageFormat-AMF
https://github.com/seanpm2001/Learn-ApacheAvro
https://github.com/seanpm2001/Learn-ErlangDoc-EDOC
https://github.com/seanpm2001/Learn-TSV-Tab-Separated-Values
https://github.com/seanpm2001/Learn-Web-Ontology-Language
https://github.com/seanpm2001/Learn-MATH-MATIC
https://github.com/seanpm2001/Learn-PDDL
https://github.com/seanpm2001/Learn-Lasso
https://github.com/seanpm2001/Learn-Elvish
https://github.com/seanpm2001/Learn-NuShell
https://github.com/seanpm2001/Learn-Nearley
https://github.com/seanpm2001/Learn-Datalog
https://github.com/seanpm2001/Learn-Flix
https://github.com/seanpm2001/Learn-SWRL
https://github.com/seanpm2001/Learn-SQWRL
https://github.com/seanpm2001/Learn-RuleML
https://github.com/seanpm2001/Learn-DAML
https://github.com/seanpm2001/Learn-R2ML
https://github.com/seanpm2001/Learn-RIF
https://github.com/seanpm2001/Learn-LegalXML
https://github.com/seanpm2001/Learn-LilyPond
https://github.com/seanpm2001/Learn-Git-Attributes
https://github.com/seanpm2001/Learn-CassandraQueryLanguage-CQL
https://github.com/seanpm2001/Learn-Text
https://github.com/seanpm2001/Learn-P4
https://github.com/seanpm2001/Learn-NewGRF-Meta-Language
https://github.com/seanpm2001/Learn-VRML
https://github.com/seanpm2001/Learn-Simula
https://github.com/seanpm2001/Learn-V8-Torque
https://github.com/seanpm2001/Learn-Iota
https://github.com/seanpm2001/Learn-Jot
https://github.com/seanpm2001/Learn-Zot
https://github.com/seanpm2001/Learn-MultiDimensional-eXpressions
https://github.com/seanpm2001/Learn-BNF
https://github.com/seanpm2001/Learn-Visual-Basic
https://github.com/seanpm2001/Learn-JSONiq
https://github.com/seanpm2001/Learn-JSound
https://github.com/seanpm2001/Learn-OpenFormulaSpreadsheetLanguage
https://github.com/seanpm2001/Learn-Just
https://github.com/seanpm2001/Learn-Xonsh
https://github.com/seanpm2001/Learn-Tom
https://github.com/seanpm2001/Learn-Pico
https://github.com/seanpm2001/Learn-AlexaPresentationLanguage
https://github.com/seanpm2001/Learn-AlexaConversationsDescriptionLanguage
https://github.com/seanpm2001/Learn-Google-Carbon
https://github.com/seanpm2001/Learn-DDoc
https://github.com/seanpm2001/Learn-GPS-Exchange-Format
https://github.com/seanpm2001/Learn-Bison
https://github.com/seanpm2001/Learn-PEARL
https://github.com/seanpm2001/Learn-3DMLW
https://github.com/seanpm2001/Learn-X3D
https://github.com/seanpm2001/Learn-Tao-Presentations
https://github.com/seanpm2001/Learn-Web-Application-Description-Language-WADL
https://github.com/seanpm2001/Learn-sXBL
https://github.com/seanpm2001/Learn-Keyhole-Markup-Language-KML
https://github.com/seanpm2001/Learn-Hosts-file
https://github.com/seanpm2001/Learn-QBASIC
https://github.com/seanpm2001/Learn-SmallBASIC
https://github.com/seanpm2001/Learn-Sawzall
https://github.com/seanpm2001/Learn-BQN
https://github.com/seanpm2001/Learn-KakouneScript
https://github.com/seanpm2001/Learn-CFScript
https://github.com/seanpm2001/Learn-PL-I
https://github.com/seanpm2001/Learn-Simple-File-Verification
https://github.com/seanpm2001/Learn-ChucK
https://github.com/seanpm2001/Learn-Jelly
https://github.com/seanpm2001/Learn-Charcoal
https://github.com/seanpm2001/Learn-Uiua
https://github.com/seanpm2001/Learn-Vector-Markup-Language
https://github.com/seanpm2001/Learn-Precision-Graphics-Markup-Language-PGML
https://github.com/seanpm2001/Learn-WGSL
https://github.com/seanpm2001/Learn-RecipeML
https://github.com/seanpm2001/Learn-Checksums
https://github.com/seanpm2001/Learn-D2
https://github.com/seanpm2001/Learn-Sway
https://github.com/seanpm2001/Learn-Pogoscript
https://github.com/seanpm2001/Learn-Pike
https://github.com/seanpm2001/Learn-Polar
https://github.com/seanpm2001/Learn-Whiley
https://github.com/seanpm2001/Learn-Xojo
https://github.com/seanpm2001/Learn-Zephir
https://github.com/seanpm2001/Learn-Yul
https://github.com/seanpm2001/Learn-Zimpl
https://github.com/seanpm2001/Learn-Yang
https://github.com/seanpm2001/Learn-XPages
https://github.com/seanpm2001/Learn-REALBasic
https://github.com/seanpm2001/Learn-Pyrex
https://github.com/seanpm2001/Learn-WAST
https://github.com/seanpm2001/Learn-Lezer
https://github.com/seanpm2001/Learn-Wollok
https://github.com/seanpm2001/Learn-PowerBuilder
https://github.com/seanpm2001/Learn-Cypher
https://github.com/seanpm2001/Learn-DocBook
https://github.com/seanpm2001/Learn-BBCode
https://github.com/seanpm2001/Learn-UrWeb
https://github.com/seanpm2001/Learn-Unified-Parallel-C
https://github.com/seanpm2001/Learn-Kickstart
https://github.com/seanpm2001/Learn-Kit
https://github.com/seanpm2001/Learn-KerboScript
https://github.com/seanpm2001/Learn-KiCad-Legacy-Layout
https://github.com/seanpm2001/Learn-KRL
https://github.com/seanpm2001/Learn-Kusto
https://github.com/seanpm2001/Learn-KaiTai-Struct
https://github.com/seanpm2001/Learn-Lark
https://github.com/seanpm2001/Learn-Hoon
https://github.com/seanpm2001/Learn-Cue-Sheet
https://github.com/seanpm2001/Learn-Curry
https://github.com/seanpm2001/Learn-DNS-Zone
https://github.com/seanpm2001/Learn-Easybuild
https://github.com/seanpm2001/Learn-Vyper
https://github.com/seanpm2001/Learn-Rapira
https://github.com/seanpm2001/Learn-SETL
https://github.com/seanpm2001/Learn-Binary-Lambda-Calculus
https://github.com/seanpm2001/Learn-Chicken
https://github.com/seanpm2001/Learn-Chef
https://github.com/seanpm2001/Learn-FRACTRAN
https://github.com/seanpm2001/Learn-JSFuck
https://github.com/seanpm2001/Learn-Piet
https://github.com/seanpm2001/Learn-NetLogo
https://github.com/seanpm2001/Learn-Rockstar
https://github.com/seanpm2001/Learn-Shakespeare
https://github.com/seanpm2001/Learn-FilterScript
https://github.com/seanpm2001/Learn-Unlambda
https://github.com/seanpm2001/Learn-ECL
https://github.com/seanpm2001/Learn-Slice
https://github.com/seanpm2001/Learn-Parrot
https://github.com/seanpm2001/Learn-Click
https://github.com/seanpm2001/Learn-Volt
https://github.com/seanpm2001/Learn-EdgeQL
https://github.com/seanpm2001/Learn-Edge
https://github.com/seanpm2001/Learn-Talon
https://github.com/seanpm2001/Learn-Faust
https://github.com/seanpm2001/Learn-Fennel
https://github.com/seanpm2001/Learn-Imba
https://github.com/seanpm2001/Learn-LigoLANG
https://github.com/seanpm2001/Learn-Catrobat
https://github.com/seanpm2001/Learn-CODEOWNERS
https://github.com/seanpm2001/Learn-Frege
https://github.com/seanpm2001/Learn-Grace
https://github.com/seanpm2001/Learn-Sieve
https://github.com/seanpm2001/Learn-Ink
https://github.com/seanpm2001/Learn-LoomScript
https://github.com/seanpm2001/Learn-ObjectScript
https://github.com/seanpm2001/Learn-Mint
https://github.com/seanpm2001/Learn-Nit
https://github.com/seanpm2001/Learn-Pan
https://github.com/seanpm2001/Learn-Roc
https://github.com/seanpm2001/Learn-Pep8
https://github.com/seanpm2001/Learn-Rez
https://github.com/seanpm2001/Learn-Game-Maker-Language
https://github.com/seanpm2001/Learn-Rush
https://github.com/seanpm2001/Learn-C3
https://github.com/seanpm2001/Learn-RBS
https://github.com/seanpm2001/Learn-Jolie
https://github.com/seanpm2001/Learn-IGOR-Pro
https://github.com/seanpm2001/Learn-HOCON
https://github.com/seanpm2001/Learn-Ioke
https://github.com/seanpm2001/Learn-JCL
https://github.com/seanpm2001/Learn-Janet
https://github.com/seanpm2001/Learn-Jison
https://github.com/seanpm2001/Learn-Jison-Lex
https://github.com/seanpm2001/Learn-LSL
https://github.com/seanpm2001/Learn-Luau
https://github.com/seanpm2001/Learn-Opa
https://github.com/seanpm2001/Learn-Ox
https://github.com/seanpm2001/Learn-Oz
https://github.com/seanpm2001/Learn-Pact
https://github.com/seanpm2001/Learn-Redcode
https://github.com/seanpm2001/Learn-Mirah
https://github.com/seanpm2001/Learn-Slint
https://github.com/seanpm2001/Learn-Odin
https://github.com/seanpm2001/Learn-OMGROFL
https://github.com/seanpm2001/Learn-Golo
https://github.com/seanpm2001/Learn-Turtle
https://github.com/seanpm2001/Learn-vCard
https://github.com/seanpm2001/Learn-AutoLISP

//// ----------------------------------------------------- \\\\

//// Repo count: 734

//// 1+1+732=734

//// ----------------------------------------------------- \\\\

//// See also (4):

https://github.com/seanpm2001/SNU_2D_ProgrammingTools
https://github.com/seanpm2001/Education
https://github.com/seanpm2001/Seanpm2001-Education
https://github.com/seanpm2001/Seanpm2001-Learn

//// ----------------------------------------------------- \\\\

//// Total repo count: 738 (not including SNU 2D ProgrammingTools IDE repositories, out of the 4 scope, as this would raise the count above 1,000, and wouldn't be necessary)

//// 734+4=738

//// ----------------------------------------------------- \\\\

//// File info
//// File type: URLL v3 list file (*.urll)
//// File version: 6 (2024, Tuesday, October 15th at 07:58 pm PST)
//// Line count (including blank lines and compiler line): 999

//// ----------------------------------------------------- \\\\

////* Keep this until the project is updated properly
Everything after Noop (circa 2023, August 16th)
https://github.com/seanpm2001/Learn-CPL
https://github.com/seanpm2001/Learn-FLOW-MATIC
https://github.com/seanpm2001/Learn-Information-Processing-Language
https://github.com/seanpm2001/Learn-ARITH-MATIC
https://github.com/seanpm2001/Learn-asm.js
https://github.com/seanpm2001/Learn-Planner
https://github.com/seanpm2001/Learn-POP-1
https://github.com/seanpm2001/Learn-POP-2
https://github.com/seanpm2001/Learn-MDX
https://github.com/seanpm2001/Learn-SCRIPT
https://github.com/seanpm2001/Learn-Generalized-Markup-Language-GML
https://github.com/seanpm2001/Learn-EasyScript
https://github.com/seanpm2001/Learn-APL
https://github.com/seanpm2001/Learn-CDS
https://github.com/seanpm2001/Learn-CAP
https://github.com/seanpm2001/Learn-Speedcode
https://github.com/seanpm2001/Learn-P-DoublePrime
https://github.com/seanpm2001/Learn-SKILL
https://github.com/seanpm2001/Learn-EJSS
https://github.com/seanpm2001/Learn-MDL
https://github.com/seanpm2001/Learn-Arc
https://github.com/seanpm2001/Learn-Adblock-Filter-List
https://github.com/seanpm2001/Learn-Mermaid
https://github.com/seanpm2001/Learn-VisionScript
https://github.com/seanpm2001/Learn-Smithy
https://github.com/seanpm2001/Learn-Hestia
https://github.com/seanpm2001/Learn-Visual-Basic-6-0
https://github.com/seanpm2001/Learn-EmberScript
https://github.com/seanpm2001/Learn-DenizenScript
https://github.com/seanpm2001/Learn-Marko
https://github.com/seanpm2001/Learn-ASN.1
https://github.com/seanpm2001/Learn-ActionMessageFormat-AMF
https://github.com/seanpm2001/Learn-ApacheAvro
https://github.com/seanpm2001/Learn-ErlangDoc-EDOC
https://github.com/seanpm2001/Learn-TSV-Tab-Separated-Values
https://github.com/seanpm2001/Learn-Web-Ontology-Language
https://github.com/seanpm2001/Learn-MATH-MATIC
https://github.com/seanpm2001/Learn-PDDL
https://github.com/seanpm2001/Learn-Lasso
https://github.com/seanpm2001/Learn-Elvish
https://github.com/seanpm2001/Learn-NuShell
https://github.com/seanpm2001/Learn-Nearley
https://github.com/seanpm2001/Learn-Datalog
https://github.com/seanpm2001/Learn-Flix
https://github.com/seanpm2001/Learn-SWRL
https://github.com/seanpm2001/Learn-SQWRL
https://github.com/seanpm2001/Learn-RuleML
https://github.com/seanpm2001/Learn-DAML
https://github.com/seanpm2001/Learn-R2ML
https://github.com/seanpm2001/Learn-RIF
https://github.com/seanpm2001/Learn-LegalXML
https://github.com/seanpm2001/Learn-LilyPond
https://github.com/seanpm2001/Learn-Git-Attributes
https://github.com/seanpm2001/Learn-CassandraQueryLanguage-CQL
https://github.com/seanpm2001/Learn-Text
https://github.com/seanpm2001/Learn-P4
https://github.com/seanpm2001/Learn-NewGRF-Meta-Language
https://github.com/seanpm2001/Learn-VRML
https://github.com/seanpm2001/Learn-Simula
https://github.com/seanpm2001/Learn-V8-Torque
https://github.com/seanpm2001/Learn-Iota
https://github.com/seanpm2001/Learn-Jot
https://github.com/seanpm2001/Learn-Zot
https://github.com/seanpm2001/Learn-MultiDimensional-eXpressions
https://github.com/seanpm2001/Learn-BNF
https://github.com/seanpm2001/Learn-Visual-Basic
https://github.com/seanpm2001/Learn-JSONiq
https://github.com/seanpm2001/Learn-JSound
https://github.com/seanpm2001/Learn-OpenFormulaSpreadsheetLanguage
https://github.com/seanpm2001/Learn-Just
https://github.com/seanpm2001/Learn-Xonsh
https://github.com/seanpm2001/Learn-Tom
https://github.com/seanpm2001/Learn-Pico
https://github.com/seanpm2001/Learn-AlexaPresentationLanguage
https://github.com/seanpm2001/Learn-AlexaConversationsDescriptionLanguage
https://github.com/seanpm2001/Learn-Google-Carbon
https://github.com/seanpm2001/Learn-DDoc
https://github.com/seanpm2001/Learn-GPS-Exchange-Format
https://github.com/seanpm2001/Learn-Bison
https://github.com/seanpm2001/Learn-PEARL
https://github.com/seanpm2001/Learn-3DMLW
https://github.com/seanpm2001/Learn-X3D
https://github.com/seanpm2001/Learn-Tao-Presentations
https://github.com/seanpm2001/Learn-Web-Application-Description-Language-WADL
https://github.com/seanpm2001/Learn-sXBL
https://github.com/seanpm2001/Learn-Keyhole-Markup-Language-KML
https://github.com/seanpm2001/Learn-Hosts-file
https://github.com/seanpm2001/Learn-QBASIC
https://github.com/seanpm2001/Learn-SmallBASIC
https://github.com/seanpm2001/Learn-Sawzall
https://github.com/seanpm2001/Learn-BQN
https://github.com/seanpm2001/Learn-KakouneScript
https://github.com/seanpm2001/Learn-CFScript
https://github.com/seanpm2001/Learn-PL-I
https://github.com/seanpm2001/Learn-Simple-File-Verification
https://github.com/seanpm2001/Learn-ChucK
https://github.com/seanpm2001/Learn-Jelly
https://github.com/seanpm2001/Learn-Charcoal
https://github.com/seanpm2001/Learn-Uiua
https://github.com/seanpm2001/Learn-Vector-Markup-Language
https://github.com/seanpm2001/Learn-Precision-Graphics-Markup-Language-PGML
https://github.com/seanpm2001/Learn-WGSL
https://github.com/seanpm2001/Learn-RecipeML
https://github.com/seanpm2001/Learn-Checksums
https://github.com/seanpm2001/Learn-D2
https://github.com/seanpm2001/Learn-Sway
https://github.com/seanpm2001/Learn-Pogoscript
https://github.com/seanpm2001/Learn-Pike
https://github.com/seanpm2001/Learn-Polar
https://github.com/seanpm2001/Learn-Whiley
https://github.com/seanpm2001/Learn-Xojo
https://github.com/seanpm2001/Learn-Zephir
https://github.com/seanpm2001/Learn-Yul
https://github.com/seanpm2001/Learn-Zimpl
https://github.com/seanpm2001/Learn-Yang
https://github.com/seanpm2001/Learn-XPages
https://github.com/seanpm2001/Learn-REALBasic
https://github.com/seanpm2001/Learn-Pyrex
https://github.com/seanpm2001/Learn-WAST
https://github.com/seanpm2001/Learn-Lezer
https://github.com/seanpm2001/Learn-Wollok
https://github.com/seanpm2001/Learn-PowerBuilder
https://github.com/seanpm2001/Learn-Cypher
https://github.com/seanpm2001/Learn-DocBook
https://github.com/seanpm2001/Learn-BBCode
https://github.com/seanpm2001/Learn-UrWeb
https://github.com/seanpm2001/Learn-Unified-Parallel-C
https://github.com/seanpm2001/Learn-Kickstart
https://github.com/seanpm2001/Learn-Kit
https://github.com/seanpm2001/Learn-KerboScript
https://github.com/seanpm2001/Learn-KiCad-Legacy-Layout
https://github.com/seanpm2001/Learn-KRL
https://github.com/seanpm2001/Learn-Kusto
https://github.com/seanpm2001/Learn-KaiTai-Struct
https://github.com/seanpm2001/Learn-Lark
https://github.com/seanpm2001/Learn-Hoon
https://github.com/seanpm2001/Learn-Cue-Sheet
https://github.com/seanpm2001/Learn-Curry
https://github.com/seanpm2001/Learn-DNS-Zone
https://github.com/seanpm2001/Learn-Easybuild
https://github.com/seanpm2001/Learn-Vyper
https://github.com/seanpm2001/Learn-Rapira
https://github.com/seanpm2001/Learn-SETL
https://github.com/seanpm2001/Learn-Binary-Lambda-Calculus
https://github.com/seanpm2001/Learn-Chicken
https://github.com/seanpm2001/Learn-Chef
https://github.com/seanpm2001/Learn-FRACTRAN
https://github.com/seanpm2001/Learn-JSFuck
https://github.com/seanpm2001/Learn-Piet
https://github.com/seanpm2001/Learn-NetLogo
https://github.com/seanpm2001/Learn-Rockstar
https://github.com/seanpm2001/Learn-Shakespeare
https://github.com/seanpm2001/Learn-FilterScript
https://github.com/seanpm2001/Learn-Unlambda
https://github.com/seanpm2001/Learn-ECL
https://github.com/seanpm2001/Learn-Slice
https://github.com/seanpm2001/Learn-Parrot
https://github.com/seanpm2001/Learn-Click
https://github.com/seanpm2001/Learn-Volt
https://github.com/seanpm2001/Learn-EdgeQL
https://github.com/seanpm2001/Learn-Edge
https://github.com/seanpm2001/Learn-Talon
https://github.com/seanpm2001/Learn-Faust
https://github.com/seanpm2001/Learn-Fennel
https://github.com/seanpm2001/Learn-Imba
https://github.com/seanpm2001/Learn-LigoLANG
https://github.com/seanpm2001/Learn-Catrobat
https://github.com/seanpm2001/Learn-CODEOWNERS
https://github.com/seanpm2001/Learn-Frege
https://github.com/seanpm2001/Learn-Grace
https://github.com/seanpm2001/Learn-Sieve
https://github.com/seanpm2001/Learn-Ink
https://github.com/seanpm2001/Learn-LoomScript
https://github.com/seanpm2001/Learn-ObjectScript
https://github.com/seanpm2001/Learn-Mint
https://github.com/seanpm2001/Learn-Nit
https://github.com/seanpm2001/Learn-Pan
https://github.com/seanpm2001/Learn-Roc
https://github.com/seanpm2001/Learn-Pep8
https://github.com/seanpm2001/Learn-Rez
https://github.com/seanpm2001/Learn-Game-Maker-Language
https://github.com/seanpm2001/Learn-Rush
https://github.com/seanpm2001/Learn-C3
https://github.com/seanpm2001/Learn-RBS
https://github.com/seanpm2001/Learn-Jolie
https://github.com/seanpm2001/Learn-IGOR-Pro
https://github.com/seanpm2001/Learn-HOCON
https://github.com/seanpm2001/Learn-Ioke
https://github.com/seanpm2001/Learn-JCL
https://github.com/seanpm2001/Learn-Janet
https://github.com/seanpm2001/Learn-Jison
https://github.com/seanpm2001/Learn-Jison-Lex
https://github.com/seanpm2001/Learn-LSL
https://github.com/seanpm2001/Learn-Luau
https://github.com/seanpm2001/Learn-Opa
https://github.com/seanpm2001/Learn-Ox
https://github.com/seanpm2001/Learn-Oz
https://github.com/seanpm2001/Learn-Pact
https://github.com/seanpm2001/Learn-Redcode
https://github.com/seanpm2001/Learn-Mirah
https://github.com/seanpm2001/Learn-Slint
https://github.com/seanpm2001/Learn-Odin
https://github.com/seanpm2001/Learn-OMGROFL
https://github.com/seanpm2001/Learn-Golo
https://github.com/seanpm2001/Learn-Turtle
https://github.com/seanpm2001/Learn-vCard
https://github.com/seanpm2001/Learn-AutoLISP
*\\\\

//// End of file
