COMMENT Comments in POP-2
WRITE(F,"POP-2 shares syntax with ALGOL. My recreation may not be exact.">);
WRITE(F,"However, statements were written in reverse order. Something like this:">);
WRITE(F"a := 1;">);
WRITE(F,"Would be written like this:">);
WRITE(F"1 -> a;">);
COMMENT This likely doesn't apply to WRITE or COMMENT
COMMENT File extension guess: *.L
COMMENT File version: 1 (2024, Tuesday, January 2nd at 4:50 pm PST)
