; Speedcode/Speedcoding/Speedco knowledge dump (2024.01.15)
; This is a comment
PRINT Speedcoding/Speedcode/Speedco program
; Speedcode has a syntax similar to Assembly
; Speedcode was the very first high-level programming language
; The language was created in 1953 for the IBM 701
; This program is going to fill the entire magnetic drum of this
; IBM 701
; File extension guess: .S
; File version: 1 (2024, Monday, January 15th at 2:19 pm PST)
